// Most primitives are dependency-free and now live in @jsonbored/ui-kit
// (the shared, app-agnostic component library) so ui-kit's own components
// can use them too. This barrel re-exports them under the same names so
// every existing "@/components/metagraphed/primitives" import site is
// unaffected. The handful still defined locally (below the re-exports)
// genuinely need apps/ui's router/query/hooks and can't move.
export {
  Chip,
  type ChipTone,
  type ChipProps,
  StatusBadge,
  type HealthStatus,
  type StatusBadgeProps,
  Indicator,
  type IndicatorProps,
  FilterField,
  FilterInput,
  FilterSelect,
  FilterToolbar,
  ColumnCustomizer,
  type ColumnCustomizerProps,
  useColumnVisibility,
  defaultVisible,
  type ColumnDef,
  Panel,
  type PanelProps,
  type PanelTone,
  SectionLabel,
  type SectionLabelProps,
  type SectionLabelSize,
  type SectionLabelTone,
  EmptyState,
  type EmptyStateProps,
  type EmptyStateVariant,
  TableSkeleton,
  type TableSkeletonProps,
  type TableSkeletonDensity,
  MetricGrid,
  type MetricGridProps,
  PanelHeader,
  type PanelHeaderProps,
  Divider,
  type DividerProps,
  TabStrip,
  type TabStripProps,
  type TabStripItem,
  StickyToolbar,
  type StickyToolbarProps,
  DefinitionList,
  type DefinitionListProps,
  type DefinitionItem,
  LoadingPill,
  type LoadingPillProps,
  GhostButton,
  type GhostButtonProps,
  type GhostButtonSize,
  type GhostButtonTone,
  PagerFooter,
  type PagerFooterProps,
  MetaStrip,
  type MetaStripProps,
  type MetaStripItem,
  ScrollShadow,
  type ScrollShadowProps,
  ResponsiveTable,
  type ResponsiveTableProps,
  FilterSheet,
  type FilterSheetProps,
  PageActions,
  type PageActionsProps,
  PanelSkeleton,
  type PanelSkeletonProps,
  type PanelSkeletonHeight,
  MobileCollapse,
  type MobileCollapseProps,
  ReadinessGauge,
  type ReadinessGaugeProps,
  ProvenanceChip,
  QueryBar,
  useQueryBarContext,
  type QueryBarProps,
  type QueryBarSearchProps,
  type QueryBarFilterOption,
  type QueryBarFilterTriggerProps,
  type QueryBarMetaRowProps,
  ChartSkeleton,
  type ChartSkeletonProps,
  PanelError,
  type PanelErrorProps,
  QueryProgress,
  type QueryProgressProps,
  FilterChipRow,
  type FilterChipRowProps,
  type FilterChipItem,
  RoutePending,
  type RoutePendingProps,
} from "@jsonbored/ui-kit";

/* Still local: genuinely coupled to apps/ui's router, query, or hooks. */
export { FreshnessPill } from "./freshness-pill";
export type { FreshnessPillProps } from "./freshness-pill";
export { Breadcrumbs } from "./breadcrumbs";
export type { BreadcrumbsProps } from "./breadcrumbs";
export { CopyLinkButton } from "./copy-link-button";
export type { CopyLinkButtonProps } from "./copy-link-button";
export { ChartCard } from "./chart-card";
export type { ChartCardProps } from "./chart-card";
export { AsyncPanel } from "./async-panel";
export type { AsyncPanelProps } from "./async-panel";
export { PageMasthead } from "./page-masthead";
