import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  artifactRelativePath,
  isGeneratedPublicArtifactRelativePath,
} from "../src/artifact-storage.ts";
import {
  artifactFilePath,
  DEPLOY_OWNED_ARTIFACTS,
  resolveBaseRemote,
} from "./lib.mjs";

type Row = Record<string, unknown>;

// Generated artifacts like openapi.json now exceed Node's default 1 MB
// execFileSync buffer, so git reads must allow plenty of headroom or the
// output overflows and throws ENOBUFS.
const GIT_OUTPUT_MAX_BUFFER = 64 * 1024 * 1024;

function main(): void {
  const changedFilesPath = valueAfter("--changed-files") || "changed-files.txt";
  const artifactRoot = valueAfter("--artifact-root") || "public/metagraph";

  const GENERATED_PUBLIC_ARTIFACTS = new Set([
    // build-summary.json moved to R2-only (#1003); only r2-manifest + types.d.ts
    // remain committed generated artifacts.
    "public/metagraph/r2-manifest.json",
    "public/metagraph/types.d.ts",
  ]);

  const submittedArtifacts = readFileSync(changedFilesPath, "utf8")
    .split(/\r?\n/)
    .map((file) => file.trim().replace(/\\/g, "/"))
    .filter(isSubmittedPublicArtifactPath);

  if (submittedArtifacts.length === 0) {
    console.log("No submitted public artifacts to verify.");
    process.exit(0);
  }

  const submittedDatasets = submittedArtifacts.filter((file) =>
    file.startsWith("public/datasets/"),
  );
  if (submittedDatasets.length > 0) {
    console.error(
      [
        "Do not commit public/datasets files; they are regenerated on build/deploy.",
        "Unexpected submitted dataset artifact(s):",
        ...submittedDatasets.map((file) => `- ${file}`),
      ].join("\n"),
    );
    process.exit(1);
  }

  for (const artifact of loadIndexedArtifacts(artifactRoot)) {
    if (isGeneratedPublicArtifactRelativePath(artifact)) {
      GENERATED_PUBLIC_ARTIFACTS.add(`public/metagraph/${artifact}`);
    }
  }

  const unknownArtifacts = submittedArtifacts.filter(
    (file) => !GENERATED_PUBLIC_ARTIFACTS.has(file),
  );

  if (unknownArtifacts.length > 0) {
    console.error(
      [
        "Submitted public artifacts must be generated by the compact artifact build.",
        "Remove arbitrary public/metagraph files or add them to the reviewed artifact contracts.",
        "Do not commit public/datasets files; they are regenerated on build/deploy.",
        "Unexpected submitted artifact(s):",
        ...unknownArtifacts.map((file) => `- ${file}`),
      ].join("\n"),
    );
    process.exit(1);
  }

  // Compare each submitted artifact against a freshly-built one by CONTENT, not bytes. A submitter
  // builds on a different OS/Node than CI (ubuntu/Node 22), so byte-exact `git diff` flags benign
  // cross-platform JSON-formatting differences (object key order and number rendering).
  // We normalize both sides by recursively sorting object keys while preserving array order,
  // because JSON array order is semantic for public artifacts and API responses.
  const mismatches: string[] = [];
  for (const artifact of submittedArtifacts) {
    if (!artifact.endsWith(".json")) {
      // Non-JSON generated files (e.g. types.d.ts) keep the strict byte check.
      if (gitDiffsFromHead(artifact)) {
        mismatches.push(`${artifact} (byte mismatch)`);
      }
      continue;
    }
    let committed: unknown;
    let rebuilt: unknown;
    try {
      committed = JSON.parse(gitShow(`HEAD:${artifact}`));
    } catch {
      mismatches.push(`${artifact} (committed version unreadable)`);
      continue;
    }
    try {
      rebuilt = JSON.parse(readFileSync(artifact, "utf8"));
    } catch {
      mismatches.push(`${artifact} (rebuilt version unreadable)`);
      continue;
    }
    if (
      canonicalArtifactJson(artifact, committed) !==
      canonicalArtifactJson(artifact, rebuilt)
    ) {
      mismatches.push(`${artifact} (content differs from a fresh build)`);
    }
  }

  if (mismatches.length > 0) {
    const { deployOwned: deployOwnedMismatches, other: otherMismatches } =
      partitionMismatches(mismatches);

    if (deployOwnedMismatches.length > 0) {
      console.error(buildDeployOwnedMismatchMessage(deployOwnedMismatches));
    }
    if (otherMismatches.length > 0) {
      console.error(
        [
          "Submitted public artifacts do not match a fresh build (content differs, not just formatting):",
          ...otherMismatches.map((file) => `- ${file}`),
          "Run `npm run build` and commit the regenerated public artifacts.",
        ].join("\n"),
      );
    }
    process.exit(1);
  }
  console.log(
    "Submitted public artifacts are reproducible (content-equivalent to a fresh build).",
  );
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main();
}

export function isSubmittedPublicArtifactPath(file: string): boolean {
  return (
    file.startsWith("public/metagraph/") || file.startsWith("public/datasets/")
  );
}

/**
 * Splits mismatch entries (e.g. "public/metagraph/r2-manifest.json (content
 * differs from a fresh build)") into deploy-owned-artifact entries, which get
 * a distinct "revert, don't rebuild" message, versus everything else, which
 * keeps the generic "run npm run build and commit" message.
 */
export function partitionMismatches(mismatches: string[]): {
  deployOwned: string[];
  other: string[];
} {
  // Match the exact "<path> (<reason>)" format this script's own mismatch
  // entries use, not a bare path-prefix `startsWith`, so a differently-named
  // file that happens to share a prefix (e.g. an unrelated
  // "public/metagraph/r2-manifest.json.bak (...)") can't be misclassified if
  // this helper is ever reused against a different string shape.
  const deployOwned = mismatches.filter((entry) =>
    (DEPLOY_OWNED_ARTIFACTS as string[]).some((file) =>
      entry.startsWith(`${file} (`),
    ),
  );
  const other = mismatches.filter((entry) => !deployOwned.includes(entry));
  return { deployOwned, other };
}

/**
 * Renders the "revert, don't rebuild" message for deploy-owned artifact
 * mismatches. Resolves the revert command's remote via resolveBaseRemote so
 * fork contributors (origin = their fork, upstream = canonical) get
 * `upstream/main`, matching the same recommendation as build.mjs's local
 * warning -- never a hardcoded `origin/main`, which is wrong on a fork.
 */
export function buildDeployOwnedMismatchMessage(
  deployOwnedMismatches: string[],
  cwd?: string,
): string {
  return [
    "Deploy/publish-pipeline-owned artifact(s) in your diff don't match a fresh build --",
    "this is EXPECTED and not something to fix by rebuilding again. These files are not",
    "reviewed contract surfaces; their committed copies on main reflect the last real",
    "publish, not your local build, and constantly drift for reasons unrelated to your PR",
    "(see .claude/skills/metagraphed/reference.md §8):",
    ...deployOwnedMismatches.map((file) => `- ${file}`),
    "",
    "Revert them and re-commit -- do not try to make them match:",
    `  git checkout ${resolveBaseRemote(cwd)}/main -- ${DEPLOY_OWNED_ARTIFACTS.join(" ")}`,
  ].join("\n");
}

/** Stable JSON: recursively sort object keys while preserving semantic array order. */
export function canonicalJson(value: unknown): string {
  return JSON.stringify(normalizeForComparison(value));
}

export function canonicalArtifactJson(
  artifactPath: string,
  value: unknown,
): string {
  const normalized = normalizeForComparison(value) as Row | unknown;
  if (
    artifactPath === "public/metagraph/r2-manifest.json" &&
    normalized &&
    typeof normalized === "object" &&
    !Array.isArray(normalized)
  ) {
    const row = normalized as Row;
    // The committed compact manifest is a publish lockfile, but its full/R2-only
    // byte totals can vary slightly across otherwise-equivalent rebuilds. Keep
    // the dual artifact entries strict while ignoring the known unstable R2
    // aggregate byte counters only when they are valid byte totals; otherwise
    // committed public manifest tampering must remain visible to the verifier.
    if (isValidByteTotal(row.full_artifact_size_bytes)) {
      delete row.full_artifact_size_bytes;
    }
    if (
      row.storage_tier_size_bytes &&
      typeof row.storage_tier_size_bytes === "object" &&
      !Array.isArray(row.storage_tier_size_bytes)
    ) {
      const storageTier = row.storage_tier_size_bytes as Row;
      if (isValidByteTotal(storageTier.r2)) {
        delete storageTier.r2;
      }
    }
  }
  return JSON.stringify(normalized);
}

function isValidByteTotal(value: unknown): boolean {
  return Number.isSafeInteger(value) && (value as number) >= 0;
}

function normalizeForComparison(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(normalizeForComparison);
  }
  if (value && typeof value === "object") {
    const out: Row = Object.create(null);
    for (const key of Object.keys(value).sort()) {
      out[key] = normalizeForComparison((value as Row)[key]);
    }
    return out;
  }
  return value;
}

function gitShow(ref: string): string {
  return execFileSync("git", ["show", ref], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    maxBuffer: GIT_OUTPUT_MAX_BUFFER,
  });
}

function gitDiffsFromHead(file: string): boolean {
  try {
    execFileSync("git", ["diff", "--exit-code", "--", file], {
      encoding: "utf8",
      stdio: "pipe",
      maxBuffer: GIT_OUTPUT_MAX_BUFFER,
    });
    return false;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOBUFS") {
      throw error;
    }
    return true;
  }
}

function loadIndexedArtifacts(rootPath: string): Set<string> {
  const artifactPaths = new Set<string>();
  // build-summary.json is R2-only (#1003) — read its index from the staging tier.
  for (const artifact of (readJsonArtifact(
    artifactFilePath("build-summary.json"),
  ).artifacts || []) as Row[]) {
    const relativePath = artifactRelativePath((artifact.path as string) || "");
    if (relativePath) {
      artifactPaths.add(relativePath);
    }
  }
  for (const artifact of (readJsonArtifact(
    path.join(rootPath, "r2-manifest.json"),
  ).artifacts || []) as Row[]) {
    const relativePath = artifactRelativePath((artifact.path as string) || "");
    if (relativePath) {
      artifactPaths.add(relativePath);
    }
  }
  return artifactPaths;
}

function readJsonArtifact(filePath: string): Row {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function valueAfter(flag: string): string | null {
  const index = process.argv.indexOf(flag);
  if (index === -1) {
    return null;
  }
  return process.argv[index + 1] || null;
}
